version: "3.9"

services:
  api-service:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_URL: 'host=postgres user=postgres_user password=postgres_password_2020 dbname=postgres_local_db port=5432'
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password_2020
      POSTGRES_DB: postgres_local_db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~