version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1
  golang:
    docker:
      - image: circleci/golang:1.15.6

jobs:
  generate_release:
    executor: node
    steps:
      - checkout
      - run:
          name: 'Generate Release'
          command: |
            sudo npm i -g @semantic-release/changelog @semantic-release/git semantic-release
            semantic-release

  run_codecov:
    executor: golang
    steps:
      - checkout
      - run:
          name: 'Run CodeCov'
          command: |
            make coverage
            bash <(curl -s https://codecov.io/bash)

  run_linter:
    executor: golang
    steps:
      - checkout
      - run:
          name: 'Run Linter'
          command: make lint

  run_tests:
    executor: golang
    steps:
      - checkout
      - run:
          name: 'Run Tests'
          command: make test

workflows:
  version: 2

  development:
    jobs:
      - run_linter:
          filters:
            branches:
              ignore: master
      - run_tests:
          filters:
            branches:
              ignore: master
      - run_codecov:
          filters:
            branches:
              ignore: master
          requires:
            - run_tests

  production:
    jobs:
      - generate_release:
          filters:
            branches:
              only: master
      - run_codecov:
          filters:
            branches:
              only: master